/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentation;

import Data.Carport;
import Data.MaterialList;
import Logic.Calculator;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

/**
 *
 * @author NoellZane
 */
public class CalculateCarportCommand extends Command
{

    @Override
    String execute(HttpServletRequest request, HttpServletResponse response) throws Exception
    {
        try
        {
        HttpSession session = request.getSession();
        int height = 220;
        String material = "DEFAULT";
        String details = "IDONTKNOW";
        String lengthText = request.getParameter("length");
        int length = Integer.parseInt(lengthText);
        
        String widthText = request.getParameter("width");
        int width = Integer.parseInt(widthText);
       
        String shedLengthText = request.getParameter("shedLength");
      
        if(shedLengthText == null){
        String shed = "NO SHED";
        int shedlength = 0;
        int shedwidth = 0;
        }else{
        String shed = "YES";
        int shedLength1 = Integer.parseInt(shedLengthText);
        int shedlength = shedLength1 - 30;
        int shedwidth = width - 30;
        }
        
      
        
        
        String roofText = request.getParameter("roof");
      
        if(roofText == null){
        int Roofslope = 0;
        }else{
        int roof = Integer.parseInt(roofText);
        int Roofslope = roof;
        }
        
        
        
        //Skal laves i databasen
        Carport carport = new Carport(length, width, "", true, width, shedLength, "generated by carport command", 0);
        MaterialList materials = Calculator.calculateMaterials(carport);
        
        session.setAttribute("materials", materials);
        request.setAttribute("message", "okay");
        request.setAttribute("message", length);
        
        return "Carport{" + "length=" + length + ", width=" + width + ", material=" + material + ", shed=" + shed + ", Roofslope=" + roofSlope + ", shedwidth=" + shedWidth + ", shedlength=" + shedLength + ", details=" + details + '}';


        }
        catch (Exception e){
        request.setAttribute("message", e.getMessage());
        }
        return "calculatedCarport";
    }
        

}
